-- MySQL Script generated by MySQL Workbench
-- Wed 21 Sep 2016 08:10:14 AM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mapper_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `centers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centers` ;

CREATE TABLE IF NOT EXISTS `centers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `studies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studies` ;

CREATE TABLE IF NOT EXISTS `studies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hosts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosts` ;

CREATE TABLE IF NOT EXISTS `hosts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis` ;

CREATE TABLE IF NOT EXISTS `pis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects` ;

CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `samples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples` ;

CREATE TABLE IF NOT EXISTS `samples` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sample_id` VARCHAR(45) NOT NULL,
  `center_id` INT(11) NOT NULL,
  `study_id` INT(11) NOT NULL,
  `pi_id` INT(11) NOT NULL,
  `host_id` INT(11) NOT NULL,
  `project_id` INT(11) NOT NULL,
  `filename` VARCHAR(45) NOT NULL,
  `run_dir` VARCHAR(45) NOT NULL,
  `fullpath` TEXT NOT NULL,
  `year` INT NULL DEFAULT NULL,
  `flagstat` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_samples_1`
    FOREIGN KEY (`center_id`)
    REFERENCES `centers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_2`
    FOREIGN KEY (`study_id`)
    REFERENCES `studies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_3`
    FOREIGN KEY (`host_id`)
    REFERENCES `hosts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_4`
    FOREIGN KEY (`pi_id`)
    REFERENCES `pis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_5`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_samples_1_idx` ON `samples` (`center_id` ASC);

CREATE INDEX `fk_samples_2_idx` ON `samples` (`study_id` ASC);

CREATE INDEX `fk_samples_3_idx` ON `samples` (`host_id` ASC);

CREATE INDEX `fk_samples_4_idx` ON `samples` (`pi_id` ASC);

CREATE INDEX `fk_samples_5_idx` ON `samples` (`project_id` ASC);


-- -----------------------------------------------------
-- Table `fastqs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastqs` ;

CREATE TABLE IF NOT EXISTS `fastqs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sample_id` INT(11) NOT NULL,
  `build` VARCHAR(45) NOT NULL DEFAULT '38',
  `path` TEXT NOT NULL,
  `read_group` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_fastqs_1`
    FOREIGN KEY (`sample_id`)
    REFERENCES `samples` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_fastqs_1_idx` ON `fastqs` (`sample_id` ASC);


-- -----------------------------------------------------
-- Table `results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `results` ;

CREATE TABLE IF NOT EXISTS `results` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sample_id` INT(11) NOT NULL,
  `build` VARCHAR(45) NOT NULL DEFAULT '38',
  `exported_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_results_1`
    FOREIGN KEY (`sample_id`)
    REFERENCES `samples` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_results_1_idx` ON `results` (`sample_id` ASC);

CREATE UNIQUE INDEX `index3` ON `results` (`sample_id` ASC, `build` ASC);


-- -----------------------------------------------------
-- Table `jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobs` ;

CREATE TABLE IF NOT EXISTS `jobs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `result_id` INT(11) NOT NULL,
  `job_id` INT(11) NOT NULL,
  `cluster` VARCHAR(45) NOT NULL,
  `procs` INT(11) NOT NULL,
  `memory` INT(11) NOT NULL,
  `walltime` VARCHAR(45) NOT NULL,
  `exit_code` INT(11) NULL DEFAULT NULL,
  `elapsed` INT(11) NULL DEFAULT '0',
  `node` VARCHAR(45) NULL DEFAULT NULL,
  `delay` INT(11) NULL DEFAULT '0',
  `submitted_at` DATETIME NULL DEFAULT NULL,
  `started_at` DATETIME NULL DEFAULT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_jobs_1`
    FOREIGN KEY (`result_id`)
    REFERENCES `results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `index4` ON `jobs` (`cluster` ASC);

CREATE INDEX `fk_jobs_1_idx` ON `jobs` (`result_id` ASC);

CREATE INDEX `index5` ON `jobs` (`job_id` ASC);


-- -----------------------------------------------------
-- Table `logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logs` ;

CREATE TABLE IF NOT EXISTS `logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `job_id` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `level` VARCHAR(45) NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_1`
    FOREIGN KEY (`job_id`)
    REFERENCES `jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_table1_1_idx` ON `logs` (`job_id` ASC);


-- -----------------------------------------------------
-- Table `states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `states` ;

CREATE TABLE IF NOT EXISTS `states` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `name_UNIQUE` ON `states` (`name` ASC);

CREATE INDEX `index3` ON `states` (`name` ASC);


-- -----------------------------------------------------
-- Table `steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steps` ;

CREATE TABLE IF NOT EXISTS `steps` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT 'all',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `name_UNIQUE` ON `steps` (`name` ASC);

CREATE INDEX `index3` ON `steps` (`name` ASC);


-- -----------------------------------------------------
-- Table `results_states_steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `results_states_steps` ;

CREATE TABLE IF NOT EXISTS `results_states_steps` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `result_id` INT(11) NOT NULL,
  `state_id` INT(11) NOT NULL,
  `step_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_results_states_steps_1`
    FOREIGN KEY (`result_id`)
    REFERENCES `results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_states_steps_2`
    FOREIGN KEY (`state_id`)
    REFERENCES `states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_states_steps_3`
    FOREIGN KEY (`step_id`)
    REFERENCES `steps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_results_states_steps_2_idx` ON `results_states_steps` (`state_id` ASC);

CREATE INDEX `fk_results_states_steps_3_idx` ON `results_states_steps` (`step_id` ASC);

CREATE INDEX `index4` ON `results_states_steps` (`result_id` ASC);

CREATE INDEX `index5` ON `results_states_steps` (`state_id` ASC);

CREATE INDEX `index6` ON `results_states_steps` (`step_id` ASC);

CREATE INDEX `index7` ON `results_states_steps` (`result_id` ASC, `created_at` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `states`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'failed');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'requested');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'cancelled');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'submitted');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'started');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'completed');

COMMIT;


-- -----------------------------------------------------
-- Data for table `steps`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'all');
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'bam2fastq');
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'local-align');
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'cloud-align');
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'mapping');
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'merging');
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'exported');

COMMIT;

