-- MySQL Script generated by MySQL Workbench
-- Thu 18 Feb 2016 11:30:33 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema csgmapper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `centers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centers` ;

CREATE TABLE IF NOT EXISTS `centers` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studies` ;

CREATE TABLE IF NOT EXISTS `studies` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hosts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosts` ;

CREATE TABLE IF NOT EXISTS `hosts` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis` ;

CREATE TABLE IF NOT EXISTS `pis` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects` ;

CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples` ;

CREATE TABLE IF NOT EXISTS `samples` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sample_id` VARCHAR(45) NOT NULL COMMENT '',
  `center_id` INT NOT NULL COMMENT '',
  `study_id` INT NOT NULL COMMENT '',
  `pi_id` INT NOT NULL COMMENT '',
  `host_id` INT NOT NULL COMMENT '',
  `project_id` INT NOT NULL COMMENT '',
  `filename` VARCHAR(45) NOT NULL COMMENT '',
  `run_dir` VARCHAR(45) NOT NULL COMMENT '',
  `fullpath` TEXT NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_samples_1_idx` (`center_id` ASC)  COMMENT '',
  INDEX `fk_samples_2_idx` (`study_id` ASC)  COMMENT '',
  INDEX `fk_samples_3_idx` (`host_id` ASC)  COMMENT '',
  INDEX `fk_samples_4_idx` (`pi_id` ASC)  COMMENT '',
  INDEX `fk_samples_5_idx` (`project_id` ASC)  COMMENT '',
  CONSTRAINT `fk_samples_1`
    FOREIGN KEY (`center_id`)
    REFERENCES `centers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_2`
    FOREIGN KEY (`study_id`)
    REFERENCES `studies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_3`
    FOREIGN KEY (`host_id`)
    REFERENCES `hosts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_4`
    FOREIGN KEY (`pi_id`)
    REFERENCES `pis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_5`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `states` ;

CREATE TABLE IF NOT EXISTS `states` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  INDEX `index3` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `results` ;

CREATE TABLE IF NOT EXISTS `results` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sample_id` INT NOT NULL COMMENT '',
  `state_id` INT NOT NULL COMMENT '',
  `build` VARCHAR(45) NOT NULL DEFAULT '38' COMMENT '',
  `exported_at` DATETIME NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_results_1_idx` (`sample_id` ASC)  COMMENT '',
  INDEX `fk_results_2_idx` (`state_id` ASC)  COMMENT '',
  CONSTRAINT `fk_results_1`
    FOREIGN KEY (`sample_id`)
    REFERENCES `samples` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_2`
    FOREIGN KEY (`state_id`)
    REFERENCES `states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steps` ;

CREATE TABLE IF NOT EXISTS `steps` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL DEFAULT 'all' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  INDEX `index3` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobs` ;

CREATE TABLE IF NOT EXISTS `jobs` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `result_id` INT(11) NOT NULL COMMENT '',
  `job_id` INT NOT NULL COMMENT '',
  `step_id` INT NOT NULL COMMENT '',
  `cluster` VARCHAR(45) NOT NULL COMMENT '',
  `procs` INT NOT NULL COMMENT '',
  `memory` INT(11) NOT NULL COMMENT '',
  `walltime` VARCHAR(45) NOT NULL COMMENT '',
  `exit_code` INT NULL COMMENT '',
  `elapsed` INT(11) NULL DEFAULT 0 COMMENT '',
  `node` VARCHAR(45) NULL COMMENT '',
  `delay` INT NULL DEFAULT 0 COMMENT '',
  `submitted_at` DATETIME NULL COMMENT '',
  `started_at` DATETIME NULL COMMENT '',
  `ended_at` DATETIME NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `index4` (`cluster` ASC)  COMMENT '',
  INDEX `fk_jobs_2_idx` (`step_id` ASC)  COMMENT '',
  INDEX `fk_jobs_1_idx` (`result_id` ASC)  COMMENT '',
  CONSTRAINT `fk_jobs_1`
    FOREIGN KEY (`result_id`)
    REFERENCES `results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_2`
    FOREIGN KEY (`step_id`)
    REFERENCES `steps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logs` ;

CREATE TABLE IF NOT EXISTS `logs` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `job_id` INT(11) NOT NULL COMMENT '',
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `level` VARCHAR(45) NOT NULL COMMENT '',
  `message` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_table1_1_idx` (`job_id` ASC)  COMMENT '',
  CONSTRAINT `fk_table1_1`
    FOREIGN KEY (`job_id`)
    REFERENCES `jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `states`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'failed');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'requested');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'cancelled');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'submitted');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'completed');
INSERT INTO `states` (`id`, `name`) VALUES (DEFAULT, 'started');

COMMIT;


-- -----------------------------------------------------
-- Data for table `steps`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'bam2fastq');
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'align');
INSERT INTO `steps` (`id`, `name`) VALUES (DEFAULT, 'all');

COMMIT;

